### ISSUE TITLE
Investigar relevancia de mercado de los sistemas de computación en medicina

### ISSUE THREAD

**Issue by araneda-alejandro** [HeraclitoDeEfeso/caminador#8]

**Comment by CintiaCapece** [comment]
Investigado con el enfoque los tipos de productos similares (a Realwalker )que hay en el mercado. Está reflejado en el informe/presentación.

Devolución de los profes: Ellos ya conocen los productos y no esperan que se los vendamos sino que el enfoque era mas abarcativo para el contexto de las unidades de procesamiento que utiliza cada uno.

@HeraclitoDeEfeso mandar email preguntando este tema ( "nadie  va a publicar esa info ")
